apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolioassistant
  namespace: stock-trader
  labels:
    app: portfolioassistant-stock-trader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolioassistant
  template:
    metadata:
      labels:
        app: portfolioassistant
      annotations:
        git-repo: "https://github.com/IBMStockTrader/PortfolioAssistant"
    spec:
      containers:
      - name: portfolioassistant
        image: portfolioassistantacr.azurecr.io/ibmstocktrader/portfolioassistant:latest
        ports:
          - containerPort: 8080
          - containerPort: 8443
        imagePullPolicy: Always
        env:
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: azure-openai-secret
              key: AZURE_OPENAI_API_KEY
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: azure-openai-secret
              key: AZURE_OPENAI_ENDPOINT
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
            ephemeral-storage: 256Mi
          requests:
            cpu: 500m
            memory: 1Gi
            ephemeral-storage: 32Mi
      imagePullSecrets:
        - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: portfolioassistant-service
  namespace: stock-trader
  labels:
    app: portfolioassistant
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    app: portfolioassistant
